### ISSUE TITLE
Capability to disable logs

### ISSUE THREAD

**Issue by tiberiu89** [ufoscout/docker-compose-wait#47]
It would be nice to be able to disable logging output by choice(thinking of an env variable). This could help in production where we send logs to ELK and usually we send them in JSON format, so we don't really want this extra logs there.

**Comment by tiberiu89** [comment]
In the meantime I found a workaround that might be enough, so it's up to you if you want to close the issue

Basically I ended up changing the command of the container and send the logs to /dev/null only for this command
```
CMD /wait > /dev/null 2>&1 && ...
```

**Comment by ufoscout** [comment]
@tiberiu89 
This would be pretty simple to implement; anyway, I would never use a tool that can prevent my application to start without any feedback.
I will double think about this, maybe introducing a configurable logger level would be a better approach.

**Comment by ufoscout** [comment]
In version 2.8.0, you can now disable the logs with the `WAIT_LOGGER_LEVEL` environment variable. E.g.:
```yml
  mySuperApp:
    image: "mySuperApp:latest"
    hostname: mySuperApp
    environment:
      WAIT_LOGGER_LEVEL: off
```
