### ISSUE TITLE
Added wait script but not working

### ISSUE THREAD

**Issue by kapilsoni2013** [ufoscout/docker-compose-wait#59]
Check my **dockerFile** and **docker compose**  **_config-server_** is not waiting for **MYSQL_SERVER** to complete.

**#Dockerfile**
```
FROM openjdk:8
EXPOSE 8888
WORKDIR usr/jpop
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait wait
RUN chmod +x wait
COPY ./config-server/target/config-server-0.0.1-SNAPSHOT.jar config-server-0.0.1-SNAPSHOT.jar
COPY config-store config-store
CMD wait && java -jar config-server-0.0.1-SNAPSHOT.jar
```

**#Docker Compose file**
```
version: '3'
services:
  MYSQL-SERVER:
    image: mysql:8.0.20
    container_name: MYSQL-SERVER
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./docker:/docker-entrypoint-initdb.d
    ports:
    - 3307:3306
    networks:
      - spring-cloud-network
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
  config-server:
    container_name: config-server
    build:
      context: config-store
      dockerfile: Dockerfile
    image: jpop/config-server-service:latest
    depends_on:
      - MYSQL-SERVER
    environment:
    - spring.profiles.active=native
    - spring.cloud.config.server.native.search-locations=config-store
    - WAIT_HOSTS=MYSQL-SERVER:3306
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
 volumes:
  database:
    driver: local
networks:
  spring-cloud-network:
    driver: bridge
```
