### ISSUE TITLE
docker-compose-wait doesn't start app 

### ISSUE THREAD

**Issue by dexat0r** [ufoscout/docker-compose-wait#79]
Hello! I've got an issue with docker-compose-wait on Ubuntu 20.04.

my Dockerfile:
```
FROM node:18-alpine AS development

WORKDIR /usr/src/app

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN yarn add glob rimraf

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./tsconfig.build.json .
COPY ./nest-cli.json .

# RUN yarn --frozen-lockfile --production=false

COPY [^node_modules]* .

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.12.0/wait /usr/src/wait
RUN chmod +x /usr/src/wait

ENV GIT_WORK_TREE=/usr/src/app
ENV GIT_DIR=/usr/src/app/.git
```

my docker-compose.yml:
```yml
version: "3"

services:
  app:
    container_name: 'app'
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=postgres:5432
    networks:
      - network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3021:3000
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: sh -c "/usr/src/./wait && npm run typeorm:bootstrap && npm run typeorm:migration:run && npm run typeorm:seed:run && npx nest start --watch"


  postgres:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'

networks:
  network:
    driver: bridge
```

Everything works well on macOS Ventura 13.2.1. Docker version 24.0.6

The same config on Ubuntu 20.04 doesn't start the application
After docker compose up the database starts, but docker-compose-wait doesn't catch it.
Postgres logs:
```
{"log":"\n","stream":"stdout","time":"2023-11-10T13:27:40.688396631Z"}
{"log":"PostgreSQL Database directory appears to contain a database; Skipping initialization\n","stream":"stdout","time":"2023-11-10T13:27:40.688432051Z"}
{"log":"\n","stream":"stdout","time":"2023-11-10T13:27:40.688438191Z"}
{"log":"2023-11-10 13:27:40.726 UTC [1] LOG:  starting PostgreSQL 16.0 (Debian 16.0-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit\n","stream":"stderr","time":"2023-11-10T13:27:40.727207193Z"}
{"log":"2023-11-10 13:27:40.729 UTC [1] LOG:  listening on IPv4 address \"0.0.0.0\", port 5432\n","stream":"stderr","time":"2023-11-10T13:27:40.729945457Z"}
{"log":"2023-11-10 13:27:40.729 UTC [1] LOG:  listening on IPv6 address \"::\", port 5432\n","stream":"stderr","time":"2023-11-10T13:27:40.730078787Z"}
{"log":"2023-11-10 13:27:40.734 UTC [1] LOG:  listening on Unix socket \"/var/run/postgresql/.s.PGSQL.5432\"\n","stream":"stderr","time":"2023-11-10T13:27:40.734309639Z"}
{"log":"2023-11-10 13:27:40.739 UTC [28] LOG:  database system was shut down at 2023-11-10 12:40:25 UTC\n","stream":"stderr","time":"2023-11-10T13:27:40.740877331Z"}
{"log":"2023-11-10 13:27:40.749 UTC [1] LOG:  database system is ready to accept connections\n","stream":"stderr","time":"2023-11-10T13:27:40.749522264Z"}
{"log":"2023-11-10 13:32:40.839 UTC [26] LOG:  checkpoint starting: time\n","stream":"stderr","time":"2023-11-10T13:32:40.84036884Z"}
{"log":"2023-11-10 13:32:40.851 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.013 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/1954F50, redo lsn=0/1954F18\n","stream":"stderr","time":"2023-11-10T13:32:40.852040042Z"}
```
App logs:
```
{"log":"[INFO  wait] --------------------------------------------------------\n","stream":"stderr","time":"2023-11-10T13:34:13.153880588Z"}
{"log":"[INFO  wait]  docker-compose-wait 2.12.1\n","stream":"stderr","time":"2023-11-10T13:34:13.153931698Z"}
{"log":"[INFO  wait] ---------------------------\n","stream":"stderr","time":"2023-11-10T13:34:13.153935578Z"}
{"log":"[DEBUG wait] Starting with configuration:\n","stream":"stderr","time":"2023-11-10T13:34:13.153938658Z"}
{"log":"[DEBUG wait]  - Hosts to be waiting for: [postgres:5432]\n","stream":"stderr","time":"2023-11-10T13:34:13.153941357Z"}
{"log":"[DEBUG wait]  - Paths to be waiting for: []\n","stream":"stderr","time":"2023-11-10T13:34:13.153944148Z"}
{"log":"[DEBUG wait]  - Timeout before failure: 30 seconds \n","stream":"stderr","time":"2023-11-10T13:34:13.153946597Z"}
{"log":"[DEBUG wait]  - TCP connection timeout before retry: 5 seconds \n","stream":"stderr","time":"2023-11-10T13:34:13.153949308Z"}
{"log":"[DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds\n","stream":"stderr","time":"2023-11-10T13:34:13.153951668Z"}
{"log":"[DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds\n","stream":"stderr","time":"2023-11-10T13:34:13.153954528Z"}
{"log":"[DEBUG wait]  - Sleeping time between retries: 1 seconds\n","stream":"stderr","time":"2023-11-10T13:34:13.153957157Z"}
{"log":"[DEBUG wait] --------------------------------------------------------\n","stream":"stderr","time":"2023-11-10T13:34:13.153959448Z"}
{"log":"[INFO  wait] Checking availability of host [postgres:5432]\n","stream":"stderr","time":"2023-11-10T13:34:13.153962208Z"}
{"log":"[INFO  wait] Host [postgres:5432] not yet available...\n","stream":"stderr","time":"2023-11-10T13:34:18.159907725Z"}
{"log":"[INFO  wait] Host [postgres:5432] not yet available...\n","stream":"stderr","time":"2023-11-10T13:34:24.16508254Z"}
{"log":"[INFO  wait] Host [postgres:5432] not yet available...\n","stream":"stderr","time":"2023-11-10T13:34:30.170718887Z"}
{"log":"[INFO  wait] Host [postgres:5432] not yet available...\n","stream":"stderr","time":"2023-11-10T13:34:36.177156683Z"}
{"log":"[INFO  wait] Host [postgres:5432] not yet available...\n","stream":"stderr","time":"2023-11-10T13:34:42.182452694Z"}
{"log":"[INFO  wait] Host [postgres:5432] not yet available...\n","stream":"stderr","time":"2023-11-10T13:34:48.18792846Z"}
{"log":"[ERROR wait] Timeout! After 30 seconds some hosts are still not reachable\n","stream":"stderr","time":"2023-11-10T13:34:48.187997991Z"}
```
